name: decarl
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_core: ^2.16.0
  firebase_database: ^10.2.5
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: 9.0.2
  ar_flutter_plugin: 
    git:
      https://github.com/SoroushBeigi/ar_flutter_plugin.git
  cloud_firestore: ^4.9.2
  geoflutterfire2: ^2.3.15 

      

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/map_style.json
    - assets/map_style.txt
    - assets/triangle.png
    - assets/Chicken_01/
