// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG_YH7UpuRXoFqwshRvjBa7h6tgKLata4',
    appId: '1:609017027503:android:d1a1f5da590fe22eea2d5a',
    messagingSenderId: '609017027503',
    projectId: 'decarl',
    databaseURL: 'https://decarl-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'decarl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJPlrDt6MjcTpq78g0ue96sOM2y4gvVxM',
    appId: '1:609017027503:ios:50939dd5ee0e74a5ea2d5a',
    messagingSenderId: '609017027503',
    projectId: 'decarl',
    databaseURL: 'https://decarl-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'decarl.appspot.com',
    iosClientId: '609017027503-te7u4eu0v106ohf69id3vg33uon0c9o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.decarl',
  );
}
